"""v1_initial

Revision ID: 34adb878127c
Revises: 
Create Date: 2026-05-06 18:54:30.999053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34adb878127c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('catalog_visible', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('courses', sa.Column('self_enrol_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('courses', sa.Column('price_pence', sa.Integer(), server_default='0', nullable=False))
    op.add_column('courses', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('pass_threshold', sa.Integer(), server_default='80', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'pass_threshold')
    op.drop_column('courses', 'estimated_minutes')
    op.drop_column('courses', 'price_pence')
    op.drop_column('courses', 'self_enrol_enabled')
    op.drop_column('courses', 'catalog_visible')
    # ### end Alembic commands ###
